import { assertShape, type ShapeDef } from './types';
import type { LandmarkId } from '../../data/types';

/**
 * 名所・特産のドット絵。車両スプライトと同じ「形状＋トークン」形式。
 * 形状は色を持たず、下の LANDMARK_LIVERY で着色する。
 *   K=輪郭 A=主体(白/明) B=藍(デニム) C=濃色(屋根/甲羅) D=木・茶
 *   E=緑 F=金/黄 G=窓 H=赤 P=桃色 S=石
 */

const LM_CASTLE: ShapeDef = assertShape('LM_CASTLE', {
  w: 26,
  h: 26,
  rows: [
    "..........................",
    "..........................",
    "............FF............",
    "............FF............",
    ".........CCCCCCCC.........",
    "..........AAAAAA..........",
    ".......CCCCCCCCCCCC.......",
    "........AAAAAAAAAA........",
    "........KKKKKKKKKK........",
    "........KKKKKKKKKK........",
    ".....CCCCCCCCCCCCCCCC.....",
    "......GGAAGGAAGGAAGG......",
    "......GGKKGGKKGGKKGG......",
    "......KKKKKKKKKKKKKK......",
    "...CCCCCCCCCCCCCCCCCCCC...",
    "....AAAAAAAAAAAAAAAAAA....",
    "....KKGGKKKGGKKKGGKKKK....",
    "....KKGGKKKGGKKKGGKKKK....",
    "....KKGGKKKGGKKKGGKKKK....",
    "....KKKKKKKKKKKKKKKKKK....",
    "....AAAAAAAAAAAAAAAAAA....",
    "....AAAAAAAAAAAAAAAAAA....",
    "....AAAAAAAAAAAAAAAAAA....",
    "..DDDDDDDDDDDDDDDDDDDDDD..",
    "..DDDDDDDDDDDDDDDDDDDDDD..",
    "..DDDDDDDDDDDDDDDDDDDDDD..",
  ],
});

const LM_PEACH: ShapeDef = assertShape('LM_PEACH', {
  w: 26,
  h: 26,
  rows: [
    "..........................",
    "..........................",
    "..........................",
    "............DD............",
    "............DD............",
    "............DD............",
    "............DDEEEEEEEE....",
    "............DD.EEEEEEE....",
    "..........P.DD..EEEEE.....",
    ".......HPAPPPHPPPEHEE.....",
    "......HAAAAAPHPPPPEHP.....",
    ".....HAAAAAAAHPPPPPEHP....",
    "....HPAAAAAAAHPPPPPPPHP...",
    "....HAAAAAAAAHPPPPPPPHP...",
    "....HPAAAAAAAHPPPPPPPHP...",
    "...HPPAAAAAAAHPPPPPPPPHP..",
    "....HPPAAAAAPHPPPPPPPHP...",
    "....HPPPPAPPPHPPPPPPPHP...",
    "....HPPPPPPPPHPPPPPPPHP...",
    ".....HPPPPPPPHPPPPPPHP....",
    "......HPPPPPPHPPPPPHP.....",
    ".......HPPPPPHPPPPHP......",
    "..........P..H..P.........",
    "..........................",
    "..........................",
    "..........................",
  ],
});

const LM_KURA: ShapeDef = assertShape('LM_KURA', {
  w: 26,
  h: 26,
  rows: [
    "..........................",
    "..........................",
    "..........................",
    ".........CCCCCCCC.........",
    ".......CCCCCCCCCCCC.......",
    ".....CCCCCCCCCCCCCCCC.....",
    "...CCCCCCCCCCCCCCCCCCCC...",
    "..CCCCCCCCCCCCCCCCCCCCCC..",
    ".CCCCCCCCCCCCCCCCCCCCCCCC.",
    ".KKKKKKKKKKKKKKKKKKKKKKKK.",
    "....KAAAAAAAAAAAAAAAAK....",
    "....KAGGGGAAAAAAGGGGAK....",
    "....KAGGGGAAAAAAGGGGAK....",
    "....KAGGGGAAAAAAGGGGAK....",
    "....CCCCCCCCCCCCCCCCCC....",
    "....KACACCACCACCACCACK....",
    "....KAACAACAACAACAACAK....",
    "....KAAAAAAAAAAAAAAAAK....",
    "....KACACCKKKKKKACCACK....",
    "....KAACAAKDDDDKCAACAK....",
    "....KAAAAAKDDDDKAAAAAK....",
    "....KACACCKDDDDKACCACK....",
    "....KAACAAKDDDDKCAACAK....",
    "....KAAAAAKDDDDKAAAAAK....",
    "....KKKKKKKKKKKKKKKKKK....",
    "..........................",
  ],
});

const LM_DENIM: ShapeDef = assertShape('LM_DENIM', {
  w: 26,
  h: 26,
  rows: [
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    ".....KKKKKKKKKKKKKKKK.....",
    ".....KFFFFFFFFFFFFFFK.....",
    ".....KFFFFFFFFFFFFFFK.....",
    ".....KKKKKKKKKKKKKKKK.....",
    ".....KFBBBBBBBBBBBBFK.....",
    ".....KBFFFFBBBBFFFFBK.....",
    ".....KBFBBFBBBBFBBFBK.....",
    ".....KBFBBFBBBBFBBFBK.....",
    ".....KBFFFFBKKBFFFFBK.....",
    "......KKKKKKKKKKKKKK......",
    "......KBBBBK..KBBBBK......",
    "......KBBBBK..KBBBBK......",
    "......KBBBBK..KBBBBK......",
    "......KBBBBK..KBBBBK......",
    "......KBBBBK..KBBBBK......",
    "......KBBBBK..KBBBBK......",
    "......KBBBBK..KBBBBK......",
    "......KBBBBK..KBBBBK......",
    "......KBBBBK..KBBBBK......",
    "......KBBBBK..KBBBBK......",
    "......KKKKKK..KKKKKK......",
    "..........................",
  ],
});

const LM_DOME: ShapeDef = assertShape('LM_DOME', {
  w: 26,
  h: 26,
  rows: [
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "............KK............",
    ".........AAAAAAAA.........",
    "........AAAAAAAAAA........",
    "......KAAAAAAAAAAAAK......",
    "......AAAAAAAAAAAAAA......",
    ".....AAAAAAAAAAAAAAAA.....",
    "....KAAAAAAAAAAAAAAAAK....",
    "....AAAAAAAAAAAAAAAAAA....",
    "...AAAAAAAAAAAAAAAAAAAA...",
    "...KAAAAAAAAAAAAAAAAAAK...",
    "...AAAAAAAAAAAAAAAAAAAA...",
    "...AAAAAAAAAAAAAAAAAAAA...",
    "...KAAAAAAAAAAAAAAAAAAK...",
    ".KKKKKKKKKKKKKKKKKKKKKKKK.",
    ".KKKKKKKKKKKKKKKKKKKKKKKK.",
    ".KAAGGAAGGAAGGAAGGAAGGAAK.",
    ".KAAGGAAGGAAGGAAGGAAGGAAK.",
    ".KKKKKKKKKKKKKKKKKKKKKKKK.",
    "..........................",
    "..........................",
  ],
});

const LM_CAMPUS: ShapeDef = assertShape('LM_CAMPUS', {
  w: 26,
  h: 26,
  rows: [
    "..........................",
    "..........................",
    "..........KKFKKK..........",
    "..........KFFFAK..........",
    "..........FFKFFK..........",
    "..........KFFFAK..........",
    ".CCCCCCCCCKKFKKKCCCCCCCCC.",
    "..KKKKKKKKKKKKKKKKKKKKKK..",
    "..KAAAAAAAAAAAAAAAAAAAAK..",
    "..KAGGGAGGGAGGGAGGGAGGGK..",
    "..KAGGGAGGGAGGGAGGGAGGGK..",
    "..KAGGGAGGGAGGGAGGGAGGGK..",
    "..KAAAAAAAAAAAAAAAAAAAAK..",
    "..KAGGGAGGGAGGGAGGGAGGGK..",
    "..KAGGGAGGGAGGGAGGGAGGGK..",
    "..KAGGGAGGGAGGGAGGGAGGGK..",
    "..KAAAAAAAAAAAAAAAAAAAAK..",
    "..KAGGGAGGGAGGGAGGGAGGGK..",
    "..KAGGGAGGGAGGGAGGGAGGGK..",
    "..KAGGGAGGGDDDDAGGGAGGGK..",
    "..KAAAAAAAADDDDAAAAAAAAK..",
    "..KAGGGAGGGDDDDAGGGAGGGK..",
    "..KAGGGAGGGDDDDAGGGAGGGK..",
    "..KAGGGAGGGDDDDAGGGAGGGK..",
    "..KKKKKKKKKDDDDKKKKKKKKK..",
    "..........................",
  ],
});

const LM_TORII: ShapeDef = assertShape('LM_TORII', {
  w: 26,
  h: 26,
  rows: [
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "..HHHHHHHHHHHHHHHHHHHHHH..",
    ".HHHHHHHHHHHHHHHHHHHHHHHH.",
    "..HHHHHHHHHHHHHHHHHHHHHH..",
    ".....HHH..........HHH.....",
    ".....HHH..........HHH.....",
    "....HHHHHHHHHHHHHHHHHH....",
    "....HHHHHHHHHHHHHHHHHH....",
    ".....HHH..........HHH.....",
    ".....HHH..........HHH.....",
    ".....HHH..........HHH.....",
    ".....HHH..........HHH.....",
    ".....HHH..........HHH.....",
    ".....HHH..........HHH.....",
    ".....HHH..........HHH.....",
    ".....HHH..........HHH.....",
    ".....HHH..........HHH.....",
    ".....HHH..........HHH.....",
    ".....HHH..........HHH.....",
    ".....HHH..........HHH.....",
    ".....HHH..........HHH.....",
    "..........................",
  ],
});

const LM_WISTERIA: ShapeDef = assertShape('LM_WISTERIA', {
  w: 26,
  h: 26,
  rows: [
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "..DDDDDDDDDDDDDDDDDDDDDD..",
    "..DDDDDDDDDDDDDDDDDDDDDD..",
    "..DDBB.BB.BB.BB.BB.BB.DD..",
    "..DD.BB.BB.BB.BB.BB.BBDD..",
    "..DDBB.BB.BB.BB.BB.BB.DD..",
    "..DD.BB.BB.BB.BB.BB.BBDD..",
    "..DDBB.BB.BB.BB.BB.BB.DD..",
    "..DD.BB.BB.BB.BB.BB.BBDD..",
    "..DDBB.BB.BB.BB.BB.BB.DD..",
    "..DD.BB.BB.BB.BB.BB.BBDD..",
    "..DDBB.BB.BB.BB.BB.BB.DD..",
    "..DD.BB.BB.A..BB.BB.A.DD..",
    "..DDBB.BB....BB.BB....DD..",
    "..DD.BB.BB....BB.BB...DD..",
    "..DDBB..A....BB..A....DD..",
    "..DD.BB.......BB......DD..",
    "..DDBB.......BB.......DD..",
    "..DD.A........A.......DD..",
    "..DD..................DD..",
    "..DD..................DD..",
    "..DD..................DD..",
    "..........................",
  ],
});

const LM_BRICKKILN: ShapeDef = assertShape('LM_BRICKKILN', {
  w: 26,
  h: 26,
  rows: [
    ".................A........",
    "...............A...A......",
    "................KKKKK.....",
    "................KCCCK.....",
    "................KHHHK.....",
    "................KCCCK.....",
    "................KHHHK.....",
    "................KCCCK.....",
    "................KHHHK.....",
    "................KCCCK.....",
    "................KHHHK.....",
    "................KCCCK.....",
    "..KKKKKKKKKKKKKKKKKKKK....",
    "..KHHKHHHKHHHKHHHKHHHK....",
    "..KHHHHHHHHHHHHHHHHHHK....",
    "..KKHHHKHHHKHHHKHHHKHK....",
    "..KHHHHHHHHHHHHHHHHHHK....",
    "..KHHKKKKKKKHKHHHKHHHK....",
    "..KHHHKKKKKKHHHHHHHHHK....",
    "..KKHHKKKKKKHHHKHHHKHK....",
    "..KHHHKKKKKKHHHHHHHHHK....",
    "..KHHKKKKKKKHKHHHKHHHK....",
    "..KHHHKKKKKKHHHHHHHHHK....",
    "..KKHHKKKKKKHHHKHHHKHK....",
    "..KKKKKKKKKKKKKKKKKKKK....",
    "..........................",
  ],
});

const LM_BREWERY: ShapeDef = assertShape('LM_BREWERY', {
  w: 26,
  h: 26,
  rows: [
    ".....A....................",
    "....A.....................",
    "..........................",
    "...KKKK...................",
    "...KAAK...................",
    "...KAAK...................",
    "...KAAK...KKKKK...KKKKK...",
    "...KAAK..KKKAKKK.KKKAKKK..",
    "...KAAK.KKAAAAAKKKAAAAAKK.",
    "...KAAK.KKAAAAAKKKAAAAAKK.",
    "...KAAK.KAAAAAAAKAAAAAAAK.",
    "...KKKK.KAAAAAAAKAAAAAAAK.",
    "........KAAAAAAAKAAAAAAAK.",
    "........KAAAAAAAKAAAAAAAK.",
    "........KFFFFFFFKFFFFFFFK.",
    "........KAAAAAAAKAAAAAAAK.",
    "........KAAAAAAAKAAAAAAAK.",
    "........KAAAAAAAKAAAAAAAK.",
    "........KAAAAAAAKAAAAAAAK.",
    "........KAAAAAAAKAAAAAAAK.",
    ".KKKKKKKKKKKKKKKKKKKKKKKK.",
    ".CCCCCCCCCCCCCCCCCCCCCCCC.",
    ".CCCCCCCCCCCCCCCCCCCCCCCC.",
    ".CCCCCCCCCCCCCCCCCCCCCCCC.",
    ".CCCCCCCCCCCCCCCCCCCCCCCC.",
    "..........................",
  ],
});

const LM_THATCHED: ShapeDef = assertShape('LM_THATCHED', {
  w: 26,
  h: 26,
  rows: [
    "..........................",
    "..........................",
    ".............D............",
    ".............D............",
    "............DDD...........",
    "...........DDDDD..........",
    "..........DDDDDDD.........",
    ".........DCCCCCCDD........",
    "........DDDDDDDDDDD.......",
    ".......DDDDDDDDDDDDD......",
    "......DCCCCCCCCCCCCDD.....",
    ".....DDDDDDDDDDDDDDDDD....",
    "....DDDDDDDDDDDDDDDDDDD...",
    "...DCCCCCCCCCCCCCCCCCCDD..",
    "..DDDDDDDDDDDDDDDDDDDDDDD.",
    ".DDKKKKKKKKKKKKKKKKKKKKDDD",
    "...KAAAAAAAAAAAAAAAAAAK...",
    "...KAAAAAAAAAAAAAAAAAAK...",
    "...KAAKKKKKAAAAGGGGGAAK...",
    "...KAAKKKKKAAAAGGGGGAAK...",
    "...KAAKKKKKAAAAGGGGGAAK...",
    "...KAAKKKKKAAAAGGGGGAAK...",
    "...KAAKKKKKAAAAAAAAAAAK...",
    "...KAAKKKKKAAAAAAAAAAAK...",
    "...KKKKKKKKKKKKKKKKKKKK...",
    "..........................",
  ],
});

const LM_RUINS: ShapeDef = assertShape('LM_RUINS', {
  w: 26,
  h: 26,
  rows: [
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    ".........KKKKKKKK.........",
    ".........KSSSSKSK.........",
    ".........KCSSSSCK.........",
    ".........KSSKSSSK.........",
    ".........KKKKKKKK.........",
    "......KKKKKKKKKKKKKK......",
    "......KSSSSKSSSSKSSK......",
    "......KCSSSSSSSSSSCK......",
    "......KSSKSSSSKSSSSK......",
    "......KKKKKKKKKKKKKK......",
    "....KKKKKKKKKKKKKKKKKK....",
    "....KSSKSSSSKSSSSKSSSK....",
    "....KCSSSSSSSSSSSSSSCK....",
    "....KSSSSKSSSSKSSSSKSK....",
    "....KKKKKKKKKKKKKKKKKK....",
    "..KKKKKKKKKKKKKKKKKKKKKK..",
    "..KSSKSSSSKSSSSKSSSSKSSK..",
    "..KCSSSSSSSSSSSSSSSSSSCK..",
    ".EKKKKEKKKKEKKKKEKKKKEKK..",
    "EEEEEEEEEEEEEEEEEEEEEEEEEE",
    "EEEEEEEEEEEEEEEEEEEEEEEEEE",
  ],
});

const LM_SOMEN: ShapeDef = assertShape('LM_SOMEN', {
  w: 26,
  h: 26,
  rows: [
    "..........................",
    "..........................",
    "..........................",
    "..DDDDDDDDDDDDDDDDDDDDDD..",
    "..DDDDDDDDDDDDDDDDDDDDDD..",
    "....A.A.A.A.A.A.A.A.A.....",
    "....A.A.A.A.A.A.A.A.A.....",
    "....A.A.A.A.A.A.A.A.A.....",
    "....A.A.A.A.A.A.A.A.A.....",
    "....A.A.A.A.A.A.A.A.A.....",
    "....A.A.A.A.A.A.A.A.A.....",
    "....A.A.A.A.A.A.A.A.A.....",
    "....A.A.A.A.A.A.A.A.A.....",
    "....A.A.A.A.A.A.A.A.A.....",
    "....A.A.A.A.A.A.A.A.A.....",
    "....A.A.A.A.A.A.A.A.A.....",
    "....A.A.A.A.A.A.A.A.A.....",
    "....A.A.A.A.A.A.A.A.A.....",
    "....A.A.A.A.A.A.A.A.A.....",
    "....A.A.A.A.A.A.A.A.A.....",
    "....A.A.A.A.A.A.A.A.A.....",
    "....F.F.KKKKKKKKKKF.F.....",
    "........KDDDDDDDDK........",
    "........KDDDDDDDDK........",
    "........KKKKKKKKKK........",
    "..........................",
  ],
});

const LM_RAMEN: ShapeDef = assertShape('LM_RAMEN', {
  w: 26,
  h: 26,
  rows: [
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "...................D.D....",
    ".........KKKKKKKKK.D.D....",
    ".......KKKKKAAAKKKKD.D....",
    "......KKKAAAAAAAAAKKD.D...",
    ".....KKKAAAAAAAAAAAKDKD...",
    "....KKKAAAAAAAAAAAAAKKK...",
    "....KKAAAAAAAAAAAAAAAKK...",
    "...KKAAADAAAAAAAAHAAAAKK..",
    "...CCCCDDDCCCCCCHHHCCCCC..",
    "...CCFDDDDDFCCFHHHHHFCCC..",
    "...CCCFDDDCCFCCFHHHCCFCC..",
    "...CCCCCDCCCCCCCCHCCCCCC..",
    "...KAAAAAAAAAAAAAAAAAAAK..",
    "...KKAAAAAAAAAAAAAAAAAKK..",
    "...KKAAAAAAAAAAAAAAAAAKK..",
    "...KKAAAAAAAAAAAAAAAAAKK..",
    "....KKAAAAAAAAAAAAAAAKK...",
    "....KKKAAAAAAAAAAAAAKKK...",
    ".....KKKAAAAAAAAAAAKKK....",
    "......KKKAAAAAAAAAKKK.....",
    "....KKKKKKKKKKKKKKKKKK....",
    ".........KKKKKKKKK........",
  ],
});

const LM_HORSESHOECRAB: ShapeDef = assertShape('LM_HORSESHOECRAB', {
  w: 26,
  h: 26,
  rows: [
    "..........................",
    "......CCCCCCCCCCCCCC......",
    "....CCCCCCCCCCCCCCCCCC....",
    "..CCCCCCCCCCCCCCCCCCCCCC..",
    ".CCCCFCCCCCCCCCCCCCCFCCCC.",
    "CCCCCCCCCCCCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCCCCCCCCCCCC",
    "CCC.CCCCCCCCCCCCCCCCCC.CCC",
    "CC...CCCCCCCCCCCCCCCC...CC",
    "C....DDDDDDDDDDDDDDDD....C",
    "...KKDDDDDDDDDDDDDDDDKK...",
    "....DDDDDDDDDDDDDDDDDD....",
    ".....DDDDDDDDDDDDDDDD.....",
    "......DDDDDDDDDDDDDD......",
    ".......DDDDDDDDDDDD.......",
    ".........DDDDDDDD.........",
    "..........DDDDDD..........",
    "...........CCCC...........",
    "............CC............",
    "............CC............",
    "............CC............",
    "............CC............",
    "............CC............",
    "............CC............",
    "............CC............",
  ],
});

const LM_SHINKANSEN: ShapeDef = assertShape('LM_SHINKANSEN', {
  w: 26,
  h: 26,
  rows: [
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "....KKKKKKKKKKKKKKKKKAAA..",
    "....AAAAAAAAAAAAAAAAAAAA..",
    "..AAGGGGGAGGGGGAGGGGAAAA..",
    "..AAGGGGGAGGGGGAGGGGAAA...",
    "..AAGGGGGAGGGGGAGGGGAAA...",
    "..AAGGGGGAGGGGGAGGGGAA....",
    "..AAAAAAAAAAAAAAAAAAAA....",
    "..AAAAAAAAAAAAAAAAAAAA....",
    "...BBBBBBBBBBBBBBBBBBBBB..",
    "...BBBBBBBBBBBBBBBBBBBBB..",
    "...BBBBBBBBBBBBBBBBBBBBB..",
    "..CCCCCCCCCCCCCCCCCCCCCC..",
    "..CCCCCKCCCCCCCCCCKCCCCC..",
    "......KKK........KKK......",
    ".....KKKKK......KKKKK.....",
    "......KKK........KKK......",
    ".......K..........K.......",
    "..........................",
  ],
});

const LM_SHRINEHALL: ShapeDef = assertShape('LM_SHRINEHALL', {
  w: 26,
  h: 26,
  rows: [
    "..........................",
    "..........................",
    "..........................",
    "...........CCCC...........",
    ".........CCCCCCCC.........",
    ".......CCCCCCCCCCCC.......",
    ".....CCCCCCCCCCCCCCCC.....",
    "...CCCCCCCCCCCCCCCCCCCC...",
    ".CCCCCCCCCCCCCCCCCCCCCCCC.",
    "....KKKKKKKKKKKKKKKKKK....",
    "....KAAAAAAAAAAAAAAAAK....",
    "....KADDAADDAADDAADDAK....",
    "....KADDAADDAADDAADDAK....",
    "....KADDAADDAADDAADDAK....",
    "....KADDAAKKKKKKAADDAK....",
    "....KADDAAKDDDDKAADDAK....",
    "....KADDAAKDDDDKAADDAK....",
    "....KADDAAKDDDDKAADDAK....",
    "....KADDAAKDDDDKAADDAK....",
    "....KADDAAKDDDDKAADDAK....",
    "....KADDAAKDDDDKAADDAK....",
    "....KKKKKKKKKKKKKKKKKK....",
    "..KKKKKKKKKKKKKKKKKKKKKK..",
    "..KAAAAAAAAAAAAAAAAAAAAK..",
    "..KKKKKKKKKKKKKKKKKKKKKK..",
    "..........................",
  ],
});

const LM_ATOM: ShapeDef = assertShape('LM_ATOM', {
  w: 26,
  h: 26,
  rows: [
    "..........................",
    "..........................",
    ".............H............",
    ".........BBBHHHBBB........",
    ".......BBBBBBHBBBBBB......",
    "......BBB..B...B..BBB.....",
    ".....BBB..B.....B..BBB....",
    "....BBB...B.....B...BBB...",
    "....BB...............BB...",
    "...BB.....BBBBBBB.....BB..",
    "...BB.BB.B.KKKKK.B.BB.BB..",
    "...BBB...BKKKFKKKB...BBB..",
    "...HB....BKKFFFKKB....BH..",
    "..HHH....BKFFFFFKB....HHH.",
    "...HB....BKKFFFKKB....BH..",
    "...BBB...BKKKFKKKB...BBB..",
    "...BB.BB.B.KKKKK.B.BB.BB..",
    "...BB.....BBBBBBB.....BB..",
    "....BB...............BB...",
    "....BBB...B.....B...BBB...",
    ".....BBB..B.....B..BBB....",
    "......BBB..B...B..BBB.....",
    ".......BBBBBB.BBBBBB......",
    ".........BBBBBBBBB........",
    "..........................",
    "..........................",
  ],
});

const LM_JUNCTION: ShapeDef = assertShape('LM_JUNCTION', {
  w: 26,
  h: 26,
  rows: [
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "....KKKK..................",
    "....KHCK..................",
    "....HHHK..................",
    "....KHCK..................",
    "....KFCK..................",
    "....FFFK................K.",
    "....KFCK..............KKA.",
    "....KECK............KKAA..",
    "....EEEK..........KKAA....",
    "....KKKK........KKAA......",
    ".....KK.......KKAA........",
    ".....KK.....KKAA..........",
    ".....KK...KKAA............",
    ".KKKKKKKKKAAKKKKKKKKKKKKK.",
    ".AAAAKKAAAAAAAAAAAAAAAAAA.",
    "..DDD.DDD.DDD.DDD.DDD.DDD.",
    "..DDD.DDD.DDD.DDD.DDD.DDD.",
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "..........................",
  ],
});

const LM_GATE: ShapeDef = assertShape('LM_GATE', {
  w: 26,
  h: 26,
  rows: [
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    ".........CCCCCCCC.........",
    ".......CCCCCCCCCCCC.......",
    "......CCCCCCCCCCCCCC......",
    "........KKKKKKKKKK........",
    "........KAAAAAAAAK........",
    "........KAFFFFFFAK........",
    "........KAFFFFFFAK........",
    "........KAFFFFFFAK........",
    "........KAFFFFFFAK........",
    "........KKKKKKKKKK........",
    "..........KKKKKK..........",
    "..........KAAAAK..........",
    "..........KKKKKK..........",
    "...........KKKK...........",
    "...........KAAK...........",
    "...........KAAK...........",
    "...........KAAK...........",
    "...........KKKK...........",
    ".......KKKKKKKKKKKK.......",
    ".......KAAAAAAAAAAK.......",
    ".......KKKKKKKKKKKK.......",
    "..........................",
  ],
});

export const LANDMARKS: Readonly<Record<LandmarkId, ShapeDef>> = {
  castle: LM_CASTLE,
  peach: LM_PEACH,
  kura: LM_KURA,
  denim: LM_DENIM,
  dome: LM_DOME,
  campus: LM_CAMPUS,
  torii: LM_TORII,
  wisteria: LM_WISTERIA,
  brickkiln: LM_BRICKKILN,
  brewery: LM_BREWERY,
  thatched: LM_THATCHED,
  ruins: LM_RUINS,
  somen: LM_SOMEN,
  ramen: LM_RAMEN,
  horseshoecrab: LM_HORSESHOECRAB,
  shinkansen: LM_SHINKANSEN,
  shrinehall: LM_SHRINEHALL,
  atom: LM_ATOM,
  junction: LM_JUNCTION,
  gate: LM_GATE,
};

export const LANDMARK_LIVERY = {
  K: '#2a2f38', A: '#f2efe6', B: '#3b5a9c', C: '#4a4038', D: '#8a6b4a',
  E: '#4f8f45', F: '#e8b93c', G: '#3d6d8c', H: '#c0392b',
  P: '#f2a0b0', S: '#9a958c',
} as const;
