import { assertShape, type ShapeDef } from './types';

/**
 * 車両スプライト。1文字1ピクセル、'.' は透明。
 * トークンは意味で塗り分ける（色は持たない）:
 *   K=輪郭 R=屋根 B=車体 S=帯 W=窓枠 G=ガラス D=ドア U=床下機器 L=前照灯 P=パンタグラフ
 * 色は render/palette.ts のリバリーで与える。形状5種 × 塗装9種で見た目を賄う。
 */

export const EMU_SUBURBAN_HEAD: ShapeDef = assertShape('EMU_SUBURBAN_HEAD', {
  w: 48,
  h: 22,
  rows: [
    "........PPPPPPPP................................",
    ".........P....P.................................",
    "...KRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRK.....",
    "..KRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRK...",
    ".KBBDDDDDBBBBBBBBBBBBBBDDDDDBBBBBBBBBBBBBBBBBK..",
    ".KBBDGGGDBBWWWWWBWWWWWBDGGGDBBWWWWWBWWWWBWWWWWK.",
    ".KBBDGGGDBBWGGGWBWGGGWBDGGGDBBWGGGWBWGGWBWGGGWK.",
    ".KBBDGGGDBBWGGGWBWGGGWBDGGGDBBWGGGWBWGGWBWGGGWK.",
    ".KBBDGGGDBBWGGGWBWGGGWBDGGGDBBWGGGWBWGGWBWGGGWK.",
    ".KBBDGGGDBBWWWWWBWWWWWBDGGGDBBWWWWWBWWWWBWGGGWK.",
    ".KSSDDDDDSSSSSSSSSSSSSSDDDDDSSSSSSSSSSSSSWWWWWK.",
    ".KSSDDDDDSSSSSSSSSSSSSSDDDDDSSSSSSSSSSSSSSSSSSK.",
    ".KBBDDDDDBBBBBBBBBBBBBBDDDDDBBBBBBBBBBBBBBBBBBK.",
    ".KBBDDDDDBBBBBBBBBBBBBBDDDDDBBBBBBBBBBBBBBBBBBK.",
    ".KBBDDDDDBBBBBBBBBBBBBBDDDDDBBBBBBBBBBBBBBBLLLK.",
    ".KBBDDDDDBBBBBBBBBBBBBBDDDDDBBBBBBBBBBBBBBBLLLK.",
    ".KUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUK.",
    "..KUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUK..",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
  ],
});

export const EMU_SUBURBAN_MID: ShapeDef = assertShape('EMU_SUBURBAN_MID', {
  w: 44,
  h: 22,
  rows: [
    "......PPPPPPPP..............................",
    ".......P....P...............................",
    "...KRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRK..",
    "..KRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRK.",
    ".KBDDDDDBBBBBBBBBBBBBBDDDDDBBBBBBBBBBBBBBBK.",
    ".KBDGGGDBBWWWWWBWWWWWBDGGGDBBWWWWWBWWWWWBBK.",
    ".KBDGGGDBBWGGGWBWGGGWBDGGGDBBWGGGWBWGGGWBBK.",
    ".KBDGGGDBBWGGGWBWGGGWBDGGGDBBWGGGWBWGGGWBBK.",
    ".KBDGGGDBBWGGGWBWGGGWBDGGGDBBWGGGWBWGGGWBBK.",
    ".KBDGGGDBBWWWWWBWWWWWBDGGGDBBWWWWWBWWWWWBBK.",
    ".KSDDDDDSSSSSSSSSSSSSSDDDDDSSSSSSSSSSSSSSSK.",
    ".KSDDDDDSSSSSSSSSSSSSSDDDDDSSSSSSSSSSSSSSSK.",
    ".KBDDDDDBBBBBBBBBBBBBBDDDDDBBBBBBBBBBBBBBBK.",
    ".KBDDDDDBBBBBBBBBBBBBBDDDDDBBBBBBBBBBBBBBBK.",
    ".KBDDDDDBBBBBBBBBBBBBBDDDDDBBBBBBBBBBBBBBBK.",
    ".KBDDDDDBBBBBBBBBBBBBBDDDDDBBBBBBBBBBBBBBBK.",
    ".KUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUK.",
    "..KUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUK..",
    "............................................",
    "............................................",
    "............................................",
    "............................................",
  ],
});
